export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_ERROR = 'LOAD_CONTACTS_ERROR';

export const SELECT_CONTACT_ID = 'SELECT_CONTACT_ID';

export const LOAD_INFOS = 'LOAD_INFOS';
export const LOAD_INFOS_SUCCESS = 'LOAD_INFOS_SUCCESS';
export const LOAD_INFOS_ERROR = 'LOAD_INFOS_ERROR';

export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';
export const SAVE_CONTACT_ERROR = 'SAVE_CONTACT_ERROR';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const SET_FILTER = 'SET_FILTER';